/* src/config.h.  Generated by configure.  */
/* $Id: config.h.in,v 1.2 2005/07/06 02:31:21 kyanh Exp $ */

/* Winefish LaTeX Editor
 * config.h.in - autoconf template
 *
 * Copyright (C) 2002-2004 Olivier Sessink
 * Modified for Winefish (C) 2005 2006 kyanh <kyanh@o2.pl>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

/* header files */
#ifndef HAVE_STDLIB_H /* supress warning when jconfig.h is included */
#define HAVE_STDLIB_H 1
#endif /* HAVE_STDLIB_H */

#define HAVE_UNISTD_H 1
#define HAVE_STRING_H 1
#define HAVE_STRINGS_H 1
#define HAVE_ERRNO_H 1
#define HAVE_STDIO_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_CTYPE_H 1
#define HAVE_GETOPT_H 1
#define HAVE_MATH_H 1
#define HAVE_TIME_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_FCNTL_H 1
#define HAVE_NETDB_H 1
#define HAVE_NETINET_IN_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_ARPA_INET_H 1
#define HAVE_DIRENT_H 1
#define HAVE_SYS_SELECT_H 1

#define HAVE_MALLOC_H 1
#define HAVE_NL_TYPES_H 1
#define HAVE_ALLOCA_H 1
#define HAVE_SYS_IPC_H 1
#define HAVE_SYS_MSG_H 1

/* libaspell */
#define HAVE_LIBASPELL 1

/* gnome-vfs-2.0 */
/* #undef HAVE_GNOME_VFS */

/* Define if you have the ANSI C header files.  */
#define STDC_HEADERS 1

/* Define if you have alloca, as a function or macro.  */
#define HAVE_ALLOCA 1

/* Define if using alloca.c.  */
/* #undef C_ALLOCA */

#define PACKAGE "winefish"
#define VERSION "1.3.2.6"
#define CURRENT_VERSION_NAME "winefish 1.3.2.6 LaTeX editor"

#define CONFIGURE_OPTIONS "configure "

/* debugging output */
/* #undef DEBUG */
/* #undef DEVELOPMENT */

/* find and grep for open advanced */
#define EXTERNAL_FIND "/usr/bin/find"
#define EXTERNAL_GREP "/usr/bin/grep"

/* i18n */
#define ENABLE_NLS 1

/* highlighting pattern profiling */
/* #undef HL_PROFILING */

#define HAVE_ATLEAST_GTK_2_2 1
#define HAVE_ATLEAST_GTK_2_4 1
#define HAVE_ATLEAST_GNOMEUI_2_6 1
/* #undef PLATFORM_DARWIN */

/*********************** winefish ***********************/

/* #undef HAVE_UNIKEY_GTK */
/* #undef HAVE_VNTEX */
/* #undef HAVE_CONTEXT */

/* maximum length of latex command. for command collector */
#define COMMAND_MAX_LENGTH 20
/* maximum length of autotext command /foobar */
#define AUTOTEXT_MAX_LENGTH 20
/* delimiters for recognization of latex commands */
#define DELIMITERS " `1234567890-=~!@#$%^&*()_+[]{};':\",./<>?\\|"

/* with splash screen */
/* #undef NOSPLASH */

/*********************** winefish ***********************/
